import requests
import csv
import arrow
from pathlib import Path
from apscheduler.schedulers.blocking import BlockingScheduler

# --- 配置区域 ---
# 定义存储根目录
SAVE_ROOT_PATH = Path("/Volumes/DRCC_DATA/11SPIDER_DATA/IRAN_NEWS")

# 目标 tRPC 接口
TRPC_API_URL = "https://iran.immersivetranslate.com/api/trpc/stats.hero,timeline.list,timeline.countsByType,polling.versions?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%2C%221%22%3A%7B%22json%22%3A%7B%22limit%22%3A30%2C%22offset%22%3A0%2C%22locale%22%3A%22zh-CN%22%7D%7D%2C%222%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%2C%223%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D"

# 用于内存去重的集合
processed_ids = set()


# --------------

def load_existing_ids():
    """程序启动时，从已有的 CSV 文件中加载历史 ID，防止重启后重复录入"""
    if not SAVE_ROOT_PATH.exists():
        return

    count = 0
    # 遍历存储目录下所有的 csv 文件
    for csv_file in SAVE_ROOT_PATH.glob("iran_conflict_news_*.csv"):
        try:
            with csv_file.open("r", encoding="utf-8-sig") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    # 提取每行的 id 字段并加入集合
                    if "id" in row and row["id"]:
                        processed_ids.add(str(row["id"]))
                        count += 1
        except Exception as e:
            print(f"读取历史文件 {csv_file.name} 失败: {e}")

    print(f"[*] 去重初始化完成：从历史文件中加载了 {count} 个已处理的 ID。")


def fetch_and_save_news():
    """核心抓取与清洗逻辑"""
    now_utc = arrow.utcnow()
    utc_date_str = now_utc.format('YYYY-MM-DD')

    print(f"[{now_utc.format('YYYY-MM-DD HH:mm:ss')} UTC] 正在拉取最新数据...")

    headers = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "Referer": "https://iran.immersivetranslate.com/zh-CN/",
    }

    try:
        response = requests.get(TRPC_API_URL, headers=headers, timeout=20)
        response.raise_for_status()
        data = response.json()

        if isinstance(data, list) and len(data) > 1:
            raw_items = data[1].get('result', {}).get('data', {}).get('json', {}).get('items', [])

            new_records = []
            for item in raw_items:
                news_id = str(item.get('id', ''))

                # 依赖于持久化加载后的 processed_ids 集合进行严格去重
                if news_id and news_id not in processed_ids:
                    record = {
                        "fetch_time_utc": now_utc.format('YYYY-MM-DD HH:mm:ss'),
                        "id": item.get("id", ""),
                        "eventTime": item.get("eventTime", ""),
                        "title": item.get("title", ""),
                        "description": item.get("description", ""),
                        "originalTitle": item.get("originalTitle", ""),
                        "originalDescription": item.get("originalDescription", ""),
                        "source": item.get("source", ""),
                        "sourceUrl": item.get("sourceUrl", ""),
                        "eventType": item.get("eventType", ""),
                        "contentType": item.get("contentType", ""),
                        "videoId": item.get("videoId", ""),
                        "thumbnailUrl": item.get("thumbnailUrl", ""),
                        "channelName": item.get("channelName", ""),
                        "channelId": item.get("channelId", ""),
                        "sourceLang": item.get("sourceLang", ""),
                        "isNew": item.get("isNew", ""),
                        "isAutoGenerated": item.get("isAutoGenerated", ""),
                        "contentHash": item.get("contentHash", ""),
                        "createdAt": item.get("createdAt", ""),
                        "updatedAt": item.get("updatedAt", "")
                    }
                    new_records.append(record)
                    processed_ids.add(news_id)  # 同步更新到内存

            if new_records:
                save_to_csv(new_records, utc_date_str)
            else:
                print("未发现新消息。")

    except Exception as e:
        print(f"[{arrow.utcnow().format('HH:mm:ss')} UTC] 爬取异常: {e}")


def save_to_csv(records, date_str):
    """将清洗后的记录写入对应日期的 CSV"""
    SAVE_ROOT_PATH.mkdir(parents=True, exist_ok=True)
    daily_csv_file = SAVE_ROOT_PATH / f"iran_conflict_news_{date_str}.csv"

    keys = [
        "fetch_time_utc", "id", "eventTime", "title", "description",
        "originalTitle", "originalDescription", "source", "sourceUrl",
        "eventType", "contentType", "videoId", "thumbnailUrl", "channelName",
        "channelId", "sourceLang", "isNew", "isAutoGenerated", "contentHash",
        "createdAt", "updatedAt"
    ]

    file_exists = daily_csv_file.exists()

    with daily_csv_file.open("a", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        if not file_exists:
            writer.writeheader()
        writer.writerows(records)

    print(f"成功写入 {len(records)} 条新记录到 {daily_csv_file.name}。")


def main():
    """主程序入口"""
    now_utc = arrow.utcnow()
    print(f"=== 爬虫服务启动 (当前 UTC 时间: {now_utc.format('YYYY-MM-DD HH:mm:ss')}) ===")
    print(f"数据将按天存储至: {SAVE_ROOT_PATH.absolute()} 目录下")

    # 1. 启动前先加载历史 ID，建立防线
    load_existing_ids()

    # 2. 程序启动时先立即执行一次拉取
    fetch_and_save_news()

    # 3. 注册定时任务
    scheduler = BlockingScheduler(timezone="UTC")
    scheduler.add_job(fetch_and_save_news, 'interval', minutes=10, id='iran_news_job')

    print("-" * 50)
    print("定时任务已注册，将每隔 10 分钟自动运行。按 Ctrl+C 终止服务。")
    print("-" * 50)

    try:
        scheduler.start()
    except (KeyboardInterrupt, SystemExit):
        print("\n收到终止信号，爬虫服务已停止。")


if __name__ == "__main__":
    main()